"use strict";(self.webpackChunkmy_website=self.webpackChunkmy_website||[]).push([[9717],{3905:(e,r,n)=>{n.d(r,{Zo:()=>p,kt:()=>g});var t=n(7294);function a(e,r,n){return r in e?Object.defineProperty(e,r,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[r]=n,e}function o(e,r){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(e);r&&(t=t.filter((function(r){return Object.getOwnPropertyDescriptor(e,r).enumerable}))),n.push.apply(n,t)}return n}function s(e){for(var r=1;r<arguments.length;r++){var n=null!=arguments[r]?arguments[r]:{};r%2?o(Object(n),!0).forEach((function(r){a(e,r,n[r])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(r){Object.defineProperty(e,r,Object.getOwnPropertyDescriptor(n,r))}))}return e}function i(e,r){if(null==e)return{};var n,t,a=function(e,r){if(null==e)return{};var n,t,a={},o=Object.keys(e);for(t=0;t<o.length;t++)n=o[t],r.indexOf(n)>=0||(a[n]=e[n]);return a}(e,r);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(t=0;t<o.length;t++)n=o[t],r.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var l=t.createContext({}),c=function(e){var r=t.useContext(l),n=r;return e&&(n="function"==typeof e?e(r):s(s({},r),e)),n},p=function(e){var r=c(e.components);return t.createElement(l.Provider,{value:r},e.children)},d="mdxType",h={inlineCode:"code",wrapper:function(e){var r=e.children;return t.createElement(t.Fragment,{},r)}},u=t.forwardRef((function(e,r){var n=e.components,a=e.mdxType,o=e.originalType,l=e.parentName,p=i(e,["components","mdxType","originalType","parentName"]),d=c(n),u=a,g=d["".concat(l,".").concat(u)]||d[u]||h[u]||o;return n?t.createElement(g,s(s({ref:r},p),{},{components:n})):t.createElement(g,s({ref:r},p))}));function g(e,r){var n=arguments,a=r&&r.mdxType;if("string"==typeof e||a){var o=n.length,s=new Array(o);s[0]=u;var i={};for(var l in r)hasOwnProperty.call(r,l)&&(i[l]=r[l]);i.originalType=e,i[d]="string"==typeof e?e:a,s[1]=i;for(var c=2;c<o;c++)s[c]=n[c];return t.createElement.apply(null,s)}return t.createElement.apply(null,n)}u.displayName="MDXCreateElement"},4532:(e,r,n)=>{n.r(r),n.d(r,{assets:()=>l,contentTitle:()=>s,default:()=>h,frontMatter:()=>o,metadata:()=>i,toc:()=>c});var t=n(7462),a=(n(7294),n(3905));const o={title:"Error Handling in Express",tags:["javascript","nodejs","express"],sidebar_label:"5. Error Handling in Express",sidebar_position:5},s=void 0,i={unversionedId:"Express/error_handling",id:"Express/error_handling",title:"Error Handling in Express",description:"Error handling is a crucial aspect of any application, and in Express.js, it's no different. In this blog post, we'll explore various ways to handle errors in Express, both synchronously and asynchronously, with practical examples.",source:"@site/docs/Express/5_error_handling.md",sourceDirName:"Express",slug:"/Express/error_handling",permalink:"/docs/Express/error_handling",draft:!1,editUrl:"https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/docs/Express/5_error_handling.md",tags:[{label:"javascript",permalink:"/docs/tags/javascript"},{label:"nodejs",permalink:"/docs/tags/nodejs"},{label:"express",permalink:"/docs/tags/express"}],version:"current",sidebarPosition:5,frontMatter:{title:"Error Handling in Express",tags:["javascript","nodejs","express"],sidebar_label:"5. Error Handling in Express",sidebar_position:5},sidebar:"tutorialSidebar",previous:{title:"4. Express.json()\n",permalink:"/docs/Express/json_middleware"},next:{title:"6. Express.Router()\n",permalink:"/docs/Express/router"}},l={},c=[{value:"Why Error Handling?",id:"why-error-handling",level:2},{value:"Synchronous Error Handling",id:"synchronous-error-handling",level:3},{value:"Asynchronous Error Handling",id:"asynchronous-error-handling",level:3},{value:"Using Async/Await",id:"using-asyncawait",level:3},{value:"Global Error Handler",id:"global-error-handler",level:3},{value:"Unhandled Promise Rejections",id:"unhandled-promise-rejections",level:2},{value:"Why Are Unhandled Promise Rejections Problematic?",id:"why-are-unhandled-promise-rejections-problematic",level:3},{value:"Why Can&#39;t a Global Error Handler Catch the Error?",id:"why-cant-a-global-error-handler-catch-the-error",level:3},{value:"Express 4 and <strong>Unhandled Promise Rejections</strong>",id:"express-4-and-unhandled-promise-rejections",level:3},{value:"Express 5 and Unhandled Promise Rejections",id:"express-5-and-unhandled-promise-rejections",level:3}],p={toc:c},d="wrapper";function h(e){let{components:r,...n}=e;return(0,a.kt)(d,(0,t.Z)({},p,n,{components:r,mdxType:"MDXLayout"}),(0,a.kt)("p",null,"Error handling is a crucial aspect of any application, and in Express.js, it's no different. In this blog post, we'll explore various ways to handle errors in Express, both synchronously and asynchronously, with practical examples."),(0,a.kt)("h2",{id:"why-error-handling"},"Why Error Handling?"),(0,a.kt)("p",null,"Errors are inevitable in any application. Whether it's a missing file, a broken link, or a server malfunction, errors can disrupt the user experience. Proper error handling ensures that the application can respond gracefully, providing informative feedback to the user and logging details for developers."),(0,a.kt)("h3",{id:"synchronous-error-handling"},"Synchronous Error Handling"),(0,a.kt)("p",null,"In synchronous operations, errors can be caught using the traditional ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"try/catch"))," block. Here's an example:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-jsx"},"app.get('/read-file', (req, res) => {\n  try {\n    const data = fs.readFileSync('file.txt', 'utf8');\n    res.send(data);\n  } catch (err) {\n    res.status(500).send('An error occurred while reading the file.');\n  }\n});\n")),(0,a.kt)("p",null,"In this example, if the file doesn't exist or there's an issue reading it, the catch block will handle the error, sending a 500 status code with a custom error message."),(0,a.kt)("h3",{id:"asynchronous-error-handling"},"Asynchronous Error Handling"),(0,a.kt)("p",null,"Asynchronous operations, such as reading a file using promises, require a different approach. Here's an example using promises:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-jsx"},"app.get('/read-file-async', (req, res) => {\n  fs.promises\n    .readFile('file.txt', 'utf8')\n    .then((data) => res.send(data))\n    .catch((err) =>\n      res.status(500).send('An error occurred while reading the file.')\n    );\n});\n")),(0,a.kt)("p",null,"In this case, if an error occurs, the ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"catch"))," block will handle it, just like in the synchronous example."),(0,a.kt)("h3",{id:"using-asyncawait"},"Using Async/Await"),(0,a.kt)("p",null,"With ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"async/await")),", you can write asynchronous code that looks synchronous. Here's how you can handle errors using ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"async/await")),":"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-jsx"},"app.get('/read-file-async-await', async (req, res) => {\n  try {\n    const data = await fs.promises.readFile('file.txt', 'utf8');\n    res.send(data);\n  } catch (err) {\n    res.status(500).send('An error occurred while reading the file.');\n  }\n});\n")),(0,a.kt)("h3",{id:"global-error-handler"},"Global Error Handler"),(0,a.kt)("p",null,"Express allows you to define a global error handler that can catch all unhandled errors. This acts as a safety net for your application:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-jsx"},"app.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).send('Something went wrong!');\n});\n")),(0,a.kt)("h2",{id:"unhandled-promise-rejections"},"Unhandled Promise Rejections"),(0,a.kt)("p",null,"Unhandled promise rejections occur when a promise is rejected, but there is no corresponding ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},".catch()"))," block or ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"try/catch"))," (when using ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("inlineCode",{parentName:"strong"},"async/await")),") to handle the rejection. Essentially, it's a situation where an error occurs within a promise, but there's no code to deal with that specific error."),(0,a.kt)("h3",{id:"why-are-unhandled-promise-rejections-problematic"},"Why Are Unhandled Promise Rejections Problematic?"),(0,a.kt)("ol",null,(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("strong",{parentName:"li"},"Silent Failures"),": Unhandled promise rejections can lead to silent failures, where an error occurs, but the application continues to run. This can lead to unexpected behavior and make debugging difficult."),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("strong",{parentName:"li"},"Potential Crashes"),": In some environments, unhandled promise rejections can lead to the termination of the Node.js process, causing the entire application to crash."),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("strong",{parentName:"li"},"Poor User Experience"),": Without proper error handling, users may encounter unexpected behavior or generic error messages that don't provide any insight into what went wrong.")),(0,a.kt)("h3",{id:"why-cant-a-global-error-handler-catch-the-error"},"Why Can't a Global Error Handler Catch the Error?"),(0,a.kt)("p",null,"In traditional synchronous code, uncaught errors bubble up and can be caught by a global error handler. However, promises introduce a complication because they handle errors on a per-promise basis."),(0,a.kt)("ol",null,(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("strong",{parentName:"li"},"Asynchronous Nature"),": Promises are asynchronous, meaning that they operate outside the regular synchronous flow of the code. If a promise is rejected and there's no ",(0,a.kt)("strong",{parentName:"li"},(0,a.kt)("inlineCode",{parentName:"strong"},".catch()"))," block to handle it, the error doesn't propagate to the global error handler."),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("strong",{parentName:"li"},"Isolated Error Handling"),": Each promise has its own error handling mechanism. Without a ",(0,a.kt)("strong",{parentName:"li"},(0,a.kt)("inlineCode",{parentName:"strong"},".catch()"))," block, the rejection remains confined to that specific promise, and the global error handler doesn't have access to it.")),(0,a.kt)("h3",{id:"express-4-and-unhandled-promise-rejections"},"Express 4 and ",(0,a.kt)("strong",{parentName:"h3"},"Unhandled Promise Rejections")),(0,a.kt)("p",null,"The package named ",(0,a.kt)("inlineCode",{parentName:"p"},"express-async-errors")," support to handle promises rejections in Express 4. You can use this package by installing this package from npm."),(0,a.kt)("h3",{id:"express-5-and-unhandled-promise-rejections"},"Express 5 and Unhandled Promise Rejections"),(0,a.kt)("p",null,"Starting with Express version 5, there's a built-in mechanism to catch unhandled promise rejections in the global error handler. This bridges the gap between the isolated error handling of promises and the global error handling of the application."),(0,a.kt)("p",null,"Here's an example of how you might define a global error handler in Express 5:"),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-js"},"app.use((err, req, res, next) => {\n  if (err instanceof PromiseRejectionError) {\n    // Handle promise rejection specifically\n  }\n  // General error handling\n  res.status(500).send('Something went wrong!');\n});\n")))}h.isMDXComponent=!0}}]);